# Generated by Django 2.1.1 on 2018-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('other', models.CharField(max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=100, null=True)),
                ('bool', models.BooleanField(default=True)),
                ('te', models.BooleanField(default=True)),
                ('many', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
