# Generated by Django 2.0.8 on 2018-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgc', '0002_person_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
