# Generated by Django 2.0.8 on 2018-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgc', '0003_person_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
