# Generated by Django 2.0.8 on 2018-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgc', '0004_person_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Many',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='many',
            field=models.ManyToManyField(to='rgc.Many'),
        ),
    ]
